use movies

SELECT NAME 
FROM MOVIESTAR
WHERE GENDER = 'FEMALE' AND NAME IN (SELECT NAME
									 FROM MOVIEEXEC
									 WHERE NETWORTH > 10000000);

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME
				   FROM MOVIEEXEC);

SELECT M1.TITLE
FROM MOVIE AS M1, MOVIE AS M2
WHERE M2.TITLE = 'Star Wars' AND M1.LENGTH > M2.LENGTH;

SELECT TITLE, ME2.NAME
FROM MOVIE INNER JOIN MOVIEEXEC AS ME1 ON PRODUCERC# = ME1.CERT#
		   INNER JOIN MOVIEEXEC AS ME2 ON PRODUCERC# = ME2.CERT#
WHERE ME1.NAME = 'Merv Griffin' AND ME2.NETWORTH > ME1.NETWORTH;

SELECT TITLE, PROD.NAME
FROM MOVIE JOIN (SELECT M2.NAME, M2.CERT#
				 FROM MOVIEEXEC AS M1, MOVIEEXEC AS M2
				 WHERE M1.NAME = 'Merv Griffin' AND M2.NETWORTH > M1.NETWORTH)
				 AS PROD
ON MOVIE.PRODUCERC# = PROD.CERT#;

use pc

SELECT DISTINCT MAKER
FROM product INNER JOIN PC ON  PRODUCT.MODEL = PC.MODEL
WHERE SPEED > 500;

/*To ask - why i have only one*/
SELECT top 1 price, model, code 
FROM PRINTER 
WHERE  price = (SELECT MAX(price) FROM printer);

SELECT *
FROM laptop
WHERE speed = (SELECT MIN(speed) FROM laptop);

SELECT PRICES.model, PRICES.price
FROM (select model, price FROM pc
	  UNION 
	  SELECT model, price FROM laptop
	  UNION
	  SELECT model, price FROM printer)
	  AS PRICES
WHERE price >= All (SELECT price FROM pc
	  UNION 
	  SELECT price FROM laptop
	  UNION
	  SELECT price FROM printer);

/*to ask*/
SELECT maker
FROM printer INNER JOIN product ON printer.model = product.model
WHERE color = 'y' and price <= ALL (SELECT price FROM printer);

SELECT DISTINCT maker
FROM PC INNER JOIN product ON pc.model = product.model
WHERE ram <= all (SELECT ram FROM pc);

use ships

SELECT DISTINCT country 
FROM CLASSES
WHERE numguns >= ALL (SELECT NUMGUNS FROM CLASSES);

SELECT DISTINCT CLASSES.class
FROM classes INNER JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
			INNER JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.result = 'sunk';

SELECT NAME, SHIPS.CLASS
FROM SHIPS INNER JOIN CLASSES ON ships.class = classes.class
WHERE BORE = 16;

SELECT BATTLE
FROM OUTCOMES INNER JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
WHERE CLASS = 'Kongo';

SELECT SHIPS.CLASS, NAME
FROM SHIPS INNER JOIN CLASSES  AS C ON SHIPS.CLASS = C.CLASS
WHERE NUMGUNS >= ALL (SELECT C1.NUMGUNS
					  FROM CLASSES AS C1
					  WHERE C1.BORE = C.BORE) 
